#!/bin/sh

if [ ! -e "/etc/ssh/ssh_host_rsa_key" ]; then
  ssh-keygen -t rsa -N "" -C "ssh-server" -f /etc/ssh/ssh_host_rsa_key
fi

if [ ! -e "/etc/ssh/ssh_host_ecdsa_key" ]; then
  ssh-keygen -t ecdsa -N "" -C "ssh-server" -f /etc/ssh/ssh_host_ecdsa_key
fi

if [ ! -e "/etc/ssh/ssh_host_ed25519_key" ]; then
  ssh-keygen -t ed25519 -N "" -C "ssh-server" -f /etc/ssh/ssh_host_ed25519_key
fi

/usr/sbin/sshd
php-fpm7
nginx -g 'daemon off;'
